# Generated by Django 6.0.1 on 2026-01-10 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(choices=[('safety', 'Безопасность и документы'), ('payment', 'Оплата и возврат'), ('docs', 'Документы и визы'), ('transport', 'Транспорт и логистика'), ('food', 'Питание'), ('connection', 'Связь'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source', models.CharField(choices=[('contact_form', 'Форма обратной связи'), ('callback', 'Обратный звонок'), ('chat_bot', 'Чат-бот')], max_length=50, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('converted', 'Конвертирован'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description_short', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('description_full', models.TextField(verbose_name='Полное описание')),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (базовая)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('tour_type', models.CharField(choices=[('bus_group', 'Автобусный групповой'), ('bus_small', 'Автобусный малая группа'), ('individual', 'Индивидуальный')], max_length=50, verbose_name='Тип тура')),
                ('max_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум человек')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион Грузии')),
                ('included', models.TextField(verbose_name='Что включено')),
                ('not_included', models.TextField(verbose_name='Что не включено')),
                ('program_by_days', models.JSONField(default=list, verbose_name='Программа по дням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operators/', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Туроператор',
                'verbose_name_plural': 'Туроператоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('guides', 'Путеводители'), ('tips', 'Советы'), ('culture', 'Культура и традиции'), ('news', 'Новости')], max_length=50, verbose_name='Категория')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='tours_blogp_categor_b0a2d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Свободных мест')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('full', 'Мест нет'), ('cancelled', 'Отменен')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Дата тура',
                'verbose_name_plural': 'Даты туров',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('people_count', models.PositiveIntegerField(default=1, verbose_name='Количество человек')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Телефон')], default='website', max_length=50, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tourdate', verbose_name='Дата тура')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.touroperator', verbose_name='Туроператор'),
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tours/', verbose_name='Фото')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фото тура',
                'verbose_name_plural': 'Фото туров',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('client_city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео URL')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderation_status', 'rating'], name='tours_revie_moderat_5768df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['start_date', 'status'], name='tours_tourd_start_d_a8aada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('tour', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='tours_booki_status_8462f6_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['tour_type'], name='tours_tour_tour_ty_d3b575_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['region'], name='tours_tour_region_d618d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price_base'], name='tours_tour_price_b_fc9699_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['duration_days'], name='tours_tour_duratio_11e640_idx'),
        ),
    ]
